#!/usr/bin/env bash
# cra-report-drill.sh — the CRA Art 14 reporting tabletop (v1.28.58 "Throughput").
#
# Fabricates an actively-exploited-vulnerability notice against the CURRENT
# release, walks the operator through the runbook's three clocks, stamps
# wall-clock at every step, fills the 24 h early-warning template, and prints
# a timing report. This is a TABLETOP: nothing is transmitted — the "send"
# steps print the would-be channel endpoints and record the timestamp.
#
# Usage: scripts/cra-report-drill.sh [OUTDIR]
#   OUTDIR defaults to dist/cra-drill — {24h-early-warning.md, timing-report.md}
#
# Fails loud if docs/cra-reporting-runbook.md is missing its anchors (the
# drill rehearses THE runbook, not a memory of it). No deps beyond POSIX sh +
# coreutils date. Idempotent: re-running overwrites its own outputs.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNBOOK="$REPO/docs/cra-reporting-runbook.md"
OUT="${1:-$REPO/dist/cra-drill}"
VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' "$REPO/Cargo.toml" | head -1)"

# ── the runbook must be intact — the drill rehearses its anchors ────────────
for anchor in "## 24-hour early warning" "## 72-hour notification" "## Final report" "ENISA" "CSIRT"; do
  grep -q "$anchor" "$RUNBOOK" || { echo "ERR: runbook missing anchor '$anchor' — fix docs/cra-reporting-runbook.md first" >&2; exit 1; }
done

mkdir -p "$OUT"

now() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
now_s() { date +%s; }

T0=$(now_s)
T0_HUMAN="$(now)"
AWARENESS="$T0_HUMAN"

cat <<EOF

════════════════════════════════════════════════════════════════════
 CRA Art 14 REPORTING DRILL — brain-server $VERSION
 Awareness (clock t0): $AWARENESS
 Scenario: a researcher's notice reports remote code execution in
 brain-server $VERSION's ingest parsing, exploited in the wild
 (public exploit + observed scanning). Trigger class: ACTIVELY
 EXPLOITED VULNERABILITY → the 24-hour clock is running.
════════════════════════════════════════════════════════════════════

EOF

step() { # step <label>
  printf '[%s] %s\n' "$(now)" "$1"
}

# ── step 1: classify ────────────────────────────────────────────────────────
step "1/6 classify trigger → actively exploited vulnerability (24 h clock)"
CLASSIFIED="$(now_s)"

# ── step 2: assemble artifacts (SBOM + version matrix + verify posture) ─────
step "2/6 assemble artifacts: SBOM + affected-version matrix + audit posture"
SBOM=""
if [[ -f "$REPO/sbom/brain-server-${VERSION}.cdx.json" ]]; then
  SBOM="sbom/brain-server-${VERSION}.cdx.json (existing release SBOM)"
elif command -v cargo >/dev/null 2>&1 && [[ -x "$REPO/scripts/sbom.sh" ]]; then
  if "$REPO/scripts/sbom.sh" >/dev/null 2>&1 && [[ -f "$REPO/sbom/brain-server-${VERSION}.cdx.json" ]]; then
    SBOM="sbom/brain-server-${VERSION}.cdx.json (generated during drill)"
  fi
fi
[[ -n "$SBOM" ]] || SBOM="SBOM GENERATION FAILED — resolve before the real clock"
ASSEMBLED="$(now_s)"

# ── step 3: draft the 24 h early warning from the template ──────────────────
step "3/6 draft 24 h early warning (filled template → $OUT/24h-early-warning.md)"
DRAFTED="$(now_s)"
cat > "$OUT/24h-early-warning.md" <<EOF
# 24-hour Early Warning — CRA Art 14(4) (DRILL — not transmitted)

- **Submission timestamp (UTC):** $(now)
- **Awareness timestamp (UTC):** $AWARENESS
- **Product:** brain-server $VERSION (single-binary memory server; SBOM: $SBOM)
- **Affected versions:** $VERSION and every earlier release in the same code
  path (operator consults CHANGELOG.md affected-version matrix; drill fixes it
  at "$VERSION — earlier versions under assessment").
- **Vulnerability summary:** remote code execution in the ingest parsing path
  of a crafted document, publicly exploited (fabricated drill scenario).
- **Exploitation observed:** YES — public exploit exists; scanning observed
  (drill fiction).
- **Impact under assessment:** confidentiality/integrity of the affected
  deployment's memory corpus; the deployment's audit chain remains the
  tamper-evidence layer (drill instruction: run GET /audit/verify and attach).
- **Containment advised:** stop public exposure of /ingest at the proxy;
  take the drill's operator guidance from docs/deployment.md.
- **Report class:** actively exploited vulnerability → 24 h early warning.
- **Next clocks:** 72 h notification (update + initial assessment), final
  report ≤ 1 month after notification.
- **This document:** generated by scripts/cra-report-drill.sh — a tabletop.
  Nothing was transmitted. Drill receipts are timing records only.
EOF

# ── step 4: "send" (tabletop — channels printed, receipts stamped) ───────────
step "4/6 'send' (tabletop): ENISA portal + national CSIRT endpoints printed"
echo "    → ENISA: EU reporting portal (CRA Art 14(2) entry point)"
echo "    → National CSIRT: the deployment's member state endpoint"
echo "      (runbook 'Operator blank' — filled at deploy time, not now)"
SENT="$(now_s)"

# ── step 5: 72 h + final checkpoints (tabletop — deadlines computed) ─────────
step "5/6 schedule 72 h notification + final report deadlines"
DUE_72H="$(date -u -r $((SENT + 72 * 3600)) +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u -d "@$((SENT + 72 * 3600))" +"%Y-%m-%dT%H:%M:%SZ")"
DUE_FINAL="$(date -u -r $((SENT + 30 * 24 * 3600)) +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u -d "@$((SENT + 30 * 24 * 3600))" +"%Y-%m-%dT%H:%M:%SZ")"

# ── step 6: timing report ────────────────────────────────────────────────────
step "6/6 write timing report"
DONE="$(now_s)"
ELAPSED_CLASS=$((CLASSIFIED - T0))
ELAPSED_ASSEMBLE=$((ASSEMBLED - CLASSIFIED))
ELAPSED_DRAFT=$((DRAFTED - ASSEMBLED))
ELAPSED_SEND=$((SENT - DRAFTED))
ELAPSED_TOTAL=$((SENT - T0))
BUDGET=$((24 * 3600))
REMAINING=$((BUDGET - ELAPSED_TOTAL))

cat > "$OUT/timing-report.md" <<EOF
# CRA drill timing report — brain-server $VERSION

- **Drill run at (UTC):** $AWARENESS
- **Trigger:** actively exploited vulnerability (fabricated notice) → 24 h clock

| Step | Wall stamp (UTC) | Elapsed since awareness |
|---|---|---|
| Awareness (t0) | $AWARENESS | 0 s |
| Classified trigger | $(date -u -r $CLASSIFIED +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || true) | ${ELAPSED_CLASS}s |
| Artifacts assembled (SBOM + matrix + verify) | | ${ELAPSED_ASSEMBLE}s |
| 24 h template drafted | | ${ELAPSED_DRAFT}s |
| "Sent" (tabletop receipts) | | ${ELAPSED_SEND}s |
| **Total drill elapsed** | | **${ELAPSED_TOTAL}s of a 86 400 s budget** |
| 72 h notification due | $DUE_72H | |
| Final report due | $DUE_FINAL | |

- **Margin remaining on the 24 h clock:** ${REMAINING}s
- **SBOM used:** $SBOM
- **Tabletop scope:** no transmission; receipts are timing records. The
  72 h and final-report bodies are NOT drafted in the drill — only their
  deadlines are computed (the 24 h template is the deliverable rehearsed).

## Baseline (record this in docs/cra-reporting-runbook.md)

Total elapsed ${ELAPSED_TOTAL}s (classify ${ELAPSED_CLASS}s · assemble
${ELAPSED_ASSEMBLE}s · draft ${ELAPSED_DRAFT}s · send ${ELAPSED_SEND}s).
EOF

cat "$OUT/timing-report.md"
echo
echo "OK  drill outputs in $OUT/"
